#!/bin/bash

# The script name can be found 
# in /home/sawa/.local/share/kservices5/kwin-script-quarter-tiling.desktop, 
# with field name : X-KDE-PluginKeyword=quarter-tiling

# You can use this command check wheather plugin is loaded or not
# qdbus org.kde.KWin /Scripting org.kde.kwin.Scripting.isScriptLoaded quarter-tiling

# Unload the script, the script will stop working now!
# qdbus org.kde.KWin /Scripting org.kde.kwin.Scripting.unloadScript quarter-tiling

# Load the script, this will return the object id
# qdbus org.kde.KWin /Scripting org.kde.kwin.Scripting.loadScript quarter-tiling
# 0         # return 0, 

script=quarter-tiling

qdbus org.kde.KWin /Scripting org.kde.kwin.Scripting.unloadScript $script
qdbus org.kde.KWin /Scripting org.kde.kwin.Scripting.start
